server:
  port: 8085
  max-http-header-size: 2012333
---
server:
  context-path: /

---
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
---
 eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    hostname: ${vcap.application.uris[0]:localhost:8761}
    status-page-url: https://${eureka.instance.hostname}/info
    health-check-url: https://${eureka.instance.hostname}/health
    home-page-url: https://${eureka.instance.hostname}/
    secure-virtual-host-name: https://${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}          
          