server:
  port: 8085
  max-http-header-size: 2012333
---
server:
  context-path: /
---
eureka:
  instance:
    non-secure-port: 80
    hostname: ${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}
---
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
               